[env]
platform = espressif32@6.3.2
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
	adafruit/Adafruit NeoPixel@^1.12.0
	bblanchon/ArduinoJson@^6.21.3

build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:controller]
; Production build - no debug output

[env:debug]
build_flags = ${env.build_flags} -DDEBUG=1
; Debug build - enable serial debug output

